let(a = 10, b = a ^ 3)
{
    var x = a + b;
    println(x);
};


try
{
    // Expected to fail as x is valid only inside 'let' context
    print(x);
}
catch(e)
{
    println('This error occurs because x exists only in let context.')
    println(e)
}